import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


OUT_DIR = Path("report_results/ims2_paper_form_visuals")
SOURCE_SVG = OUT_DIR / "fig08_square_rescaled_paper_style_ims2_project.svg"
HEALTHY_SAMPLES = 300
FFP = 532
Y_MIN = 0.4978
Y_MAX = 0.5084
X_MAX = 983


sns.set_theme(
    style="whitegrid",
    font="Times New Roman",
    rc={
        "font.size": 8.5,
        "axes.titlesize": 10,
        "axes.labelsize": 9,
        "xtick.labelsize": 8,
        "ytick.labelsize": 8,
        "legend.fontsize": 7.2,
        "figure.dpi": 150,
        "savefig.dpi": 300,
    },
)
plt.rcParams.update({"font.family": "Times New Roman"})


def extract_path_for_stroke(svg_text, stroke_hex):
    group_pattern = re.compile(r'<g id="line2d_\d+">(?P<block>.*?)</g>', re.S)
    path_pattern = re.compile(
        r'<path d="(?P<path>.*?)"\s+clip-path="[^"]+"\s+style="[^"]*stroke: '
        + re.escape(stroke_hex)
        + r'[^"]*"/>',
        re.S,
    )
    matches = []
    for group in group_pattern.finditer(svg_text):
        path_match = path_pattern.search(group.group("block"))
        if path_match:
            matches.append(path_match)
    if not matches:
        raise RuntimeError(f"Cannot find plotted path with stroke {stroke_hex}")
    candidates = []
    for match in matches:
        path = match.group("path")
        pairs = re.findall(r"[ML]\s*([-+]?\d+(?:\.\d+)?)\s*([-+]?\d+(?:\.\d+)?)", path)
        if not pairs:
            continue
        points = np.asarray([(float(x), float(y)) for x, y in pairs], dtype=float)
        in_axes = (
            (points[:, 0] >= 46.874531)
            & (points[:, 0] <= 346.79952)
            & (points[:, 1] >= 20.14375)
            & (points[:, 1] <= 317.858739)
        )
        candidates.append((int(np.sum(in_axes)), len(points), path))
    if not candidates:
        raise RuntimeError(f"Cannot parse plotted path with stroke {stroke_hex}")
    candidates.sort(reverse=True)
    return candidates[0][2]


def path_to_data(path_d):
    pairs = re.findall(r"[ML]\s*([-+]?\d+(?:\.\d+)?)\s*([-+]?\d+(?:\.\d+)?)", path_d)
    if not pairs:
        raise RuntimeError("Cannot parse SVG path coordinates")
    points = np.asarray([(float(x), float(y)) for x, y in pairs], dtype=float)

    # Axis box and limits were generated by fig08_square_rescaled_paper_style_ims2_project.svg.
    svg_x0, svg_x1 = 46.874531, 346.79952
    svg_y_bottom, svg_y_top = 317.858739, 20.14375

    x_data = (points[:, 0] - svg_x0) / (svg_x1 - svg_x0) * X_MAX
    y_data = Y_MIN + (svg_y_bottom - points[:, 1]) / (svg_y_bottom - svg_y_top) * (Y_MAX - Y_MIN)
    order = np.argsort(x_data)
    return x_data[order], y_data[order]


def save_fig(fig, name):
    png = OUT_DIR / f"{name}.png"
    svg = OUT_DIR / f"{name}.svg"
    fig.savefig(png, bbox_inches="tight")
    fig.savefig(svg, bbox_inches="tight")
    plt.close(fig)
    print(f"[SAVED] {png}")
    print(f"[SAVED] {svg}")


def main():
    svg_text = SOURCE_SVG.read_text(encoding="utf-8")
    hx, hy = path_to_data(extract_path_for_stroke(svg_text, "#2ca25f"))
    ux, uy = path_to_data(extract_path_for_stroke(svg_text, "#1f4eeb"))

    fig, ax = plt.subplots(figsize=(4.8, 4.8), constrained_layout=True)
    ax.axvspan(0, FFP, color="#dff6df", alpha=0.95, zorder=0)
    ax.axvspan(FFP, X_MAX, color="#f8dddd", alpha=0.95, zorder=0)

    healthy_mask = hx < HEALTHY_SAMPLES
    pred_healthy_mask = ux < FFP
    pred_faulty_mask = ux >= FFP

    ax.plot(hx[healthy_mask], hy[healthy_mask], color="#1a9c35", linewidth=0.75,
            label="HI of healthy samples")
    ax.plot(ux[pred_healthy_mask], uy[pred_healthy_mask], color="#1f4eeb", linewidth=0.75,
            label="HI of predicted healthy samples")
    ax.plot(ux[pred_faulty_mask], uy[pred_faulty_mask], color="#e41a1c", linewidth=0.75,
            label="HI of predicted faulty samples")

    ax.set_xlim(0, X_MAX)
    ax.set_ylim(Y_MIN, Y_MAX)
    ax.set_xlabel("Sample")
    ax.set_ylabel("Health Index")
    ax.set_title("Health index values of IMS-2 dataset")
    ax.grid(True, linestyle=(0, (5, 5)), linewidth=0.65, color="#cfcfcf")
    ax.legend(loc="upper left", frameon=True, fancybox=False, framealpha=1.0)

    save_fig(fig, "fig08_square_rescaled_regions_ims2_project")


if __name__ == "__main__":
    main()
